CREATE TABLE TURMA(
id VARCHAR(255) PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
datainicio DATE NOT NULL,
datafim DATE NOT NULL,
modulo INT DEFAULT 0
);

CREATE TABLE ESTUDANTE(
id VARCHAR(255) PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
data_nasc DATE NOT NULL,
turma_id VARCHAR(255) NOT NULL,
FOREIGN KEY (turma_id) REFERENCES TURMA(id)
);

CREATE TABLE HOBBY(
id VARCHAR(255) PRIMARY KEY,
nome VARCHAR(255) NOT NULL
);

CREATE TABLE ESTUDANTE_HOBBY(
id VARCHAR(255) PRIMARY KEY,
estudante_id VARCHAR(255) NOT NULL,
hobby_id VARCHAR(255) NOT NULL,
FOREIGN KEY (estudante_id) REFERENCES ESTUDANTE(id),
FOREIGN KEY (hobby_id) REFERENCES HOBBY(id)
);

CREATE TABLE DOCENTE(
id VARCHAR(255) PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
data_nasc DATE NOT NULL,
turma_id VARCHAR(255) NOT NULL,
FOREIGN KEY (turma_id) REFERENCES TURMA(id)
);

CREATE TABLE ESPECIALIDADE(
id VARCHAR(255) PRIMARY KEY,
nome VARCHAR(255) NOT NULL
);

CREATE TABLE DOCENTE_ESPECIALIDADE(
id VARCHAR(255) PRIMARY KEY,
docente_id VARCHAR(255) NOT NULL,
especialidade_id VARCHAR(255) NOT NULL,
FOREIGN KEY (docente_id) REFERENCES DOCENTE(id),
FOREIGN KEY (especialidade_id) REFERENCES ESPECIALIDADE(id)
);

##DROP TABLE DOCENTE_ESPECIALIDADE,ESPECIALIDADE,DOCENTE,ESTUDANTE_HOBBY,HOBBY,ESTUDANTE,TURMA;

SELECT * FROM TURMA;
SELECT * FROM DOCENTE_ESPECIALIDADE;
SELECT * FROM ESPECIALIDADE;
SELECT * FROM DOCENTE;
SELECT * FROM ESTUDANTE_HOBBY;
SELECT * FROM HOBBY;
SELECT * FROM ESTUDANTE;
